platform :ios, '7.0'
#use_frameworks!

target 'CJSliderViewControllerDemo' do
    pod "RadioButtons", "~> 2.1.3"
    pod "RadioComposeView", "~> 2.1.1"
end

target 'CJSliderViewControllerDemoTests' do
    
end
