platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

target 'CJRadioDemo' do
    pod 'CJBaseUIKit', :subspecs => ['UIButton', 'UIColor', 'UIView/CJPopupAction', 'UIViewController']
	pod 'PureLayout', '~> 3.0.2'
    pod 'Masonry'
    pod 'CJBaseUtil', :subspecs => ['CJDataUtil']
    
    pod 'SDCycleScrollView', '~> 1.73'
end

target 'CJRadioDemoTests' do
    
end
