platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

target 'CJRadioDemo' do
    pod 'CJBaseUIKit', :subspecs => ['UIColor', 'UIButton', 'UITextField', 'CJToast', 'CJAlert']
    pod 'CJBaseUIKit', :subspecs => ['UIView/CJPopupAction', 'UIViewController']
	pod 'PureLayout', '~> 3.0.2'
    pod 'Masonry'
    pod 'CJBaseUtil', :subspecs => ['CJDataUtil']

    pod 'SDCycleScrollView', '~> 1.73'
    pod 'WMPageController'
end

target 'CJRadioDemoTests' do
    
end
